module.exports ={
    head1:{
        fontSize:40,
        fontWeight:'600',
        color:'black',
        textAlign:'center',
    },
    head2:{
        fontSize:20,
        color:'black',
        textAlign:'center',
    },
    formgroup:{
        display:'flex',
        flexDirection:'column',
        width:'100%',
        marginVertical:10,
      },
      label:{
        fontSize:14,
        color:'#F50057',
        marginLeft:10,
        marginBottom:4,
      },
      input:{
        backgroundColor:'#ffb6c1',
        borderRadius:20,
        paddingHorizontal:10,
        paddingVertical:10,
      },
      input1:{
        backgroundColor:'#ffb6c1',
        borderRadius:20,
        paddingHorizontal:10,
        paddingVertical:5,
        height:50,
      },
      link:{
        color:'pink',
        fontSize:12,
      },
      link2:{
        color:'grey',
        fontSize:12,
        textAlign:'center',
        marginVertical:8
      },
      errormessage:{
        color:"black",
        fontSize:14,
        textAlign:'center',
        
        padding:4,
        borderRadius:10,
      },
      displaymessage:{
        color:'white',
        fontSize:14,
        textAlign:'center',
        backgroundColor:'black',
        padding:'5',
        borderRadius:10,
      }
}